[project]
name = "paraformer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dashscope>=1.23.1",
    "streamlit>=1.44.1",
]
